

# server port config
server:
  port: 8080  # server port

# db config
spring:
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://180.67.117.226:3306/groupware # db url
    username: feeleat                                # db username
    password: root                      # db password
  devtools:
    restart:
      enabled: false # auto restart option enabled

  # jpa config
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Logging Level
logging:
  level:
    root: info




