

# server port config
server:
  port: 8080  # server port

# db config
spring:
  mail:
    host: smtp.naver.com
    port: 587
    username:
    password:
    properties:
      smtp:
        auth: true
      starttls:
        enable: true

  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:
  devtools:
    restart:
      enabled: false # auto restart option enabled

  # jpa config
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# Logging Level
logging:
  level:
    root: info




